"""
Regenerates data/embedded-data.js from the .geojson files in data/.

Why: browsers block fetch() of local files when index.html is opened by
double-click (file://). script.js therefore falls back to this embedded copy.
If you edit any .geojson file, run:   python tools/make_embedded.py
(or simply run a local server:        python -m http.server 8000 )
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
FILES = {
    "boundary": "pakistan_boundary.geojson",
    "cities": "cities.geojson",
    "stations": "weatherstation.geojson",
    "rainfall": "rainfall.geojson",
    "environment": "environment.geojson",
}

out = ["// AUTO-GENERATED by tools/make_embedded.py - do not edit by hand.",
       "window.__GEO = window.__GEO || {};"]
for key, fname in FILES.items():
    path = os.path.join(DATA, fname)
    if not os.path.exists(path):
        continue
    with open(path, encoding="utf-8") as f:
        obj = json.load(f)
    out.append("window.__GEO[%s] = %s;" % (json.dumps(key), json.dumps(obj, separators=(",", ":"))))

with open(os.path.join(DATA, "embedded-data.js"), "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print("embedded-data.js written")
